version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - PORT=8000
    depends_on:
      - redis
    volumes:
      - ./fastf1_cache:/app/fastf1_cache

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"